FROM python:3.10-slim-bookworm

WORKDIR /app

COPY . .

RUN apt-get update --fix-missing && apt-get install
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD [ "python", "pipeline.py"]